### ISSUE TITLE
1.0.22r1 Server won't start (crashes immediatly) - java.lang.NoClassDefFoundError: joptsimple/OptionSpec

### ISSUE THREAD

**Issue by juanitierno** [Sunekaer/stoneBlock#425] opened 2018-10-20 23:50 UTC
## Bug Report
1.0.22r1 Server won't start (crashes immediatly) on the latest version. Even a clean unzip from the server zip file.

## Steps to Reproduce (for bugs)
Unzip server, run serverstart.bat.

## Logs
OS is 64
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; sup
port was removed in 8.0
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec

        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunc
hWrapper.java:52)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaun
chWrapper.java:34)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Press any key to continue . . .

## Client Information
Client starts fine.
[CRASH.txt](https://github.com/Sunekaer/stoneBlock/files/2498651/CRASH.txt)

**Comment by knoxhack** [comment] 2018-10-20 23:53
Modpack version?

**Comment by juanitierno** [comment] 2018-10-21 00:58
Sorry!  1.0.22r1

**Comment by juanitierno** [comment] 2018-10-21 01:04
Noticed there's a new version (.23)

That one crashes at the beginning too with: 
`OS is 64
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; sup
port was removed in 8.0
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunc
hWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaun
chWrapper.java:34)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
Press any key to continue . . .
`

(the install.bet did not work for me, but opened and noticed it downloads the minecraft server, so sopied it from previous version of the pack and seems to be loading.

**Comment by knoxhack** [comment] 2018-10-21 01:09
Duplicate of https://github.com/Sunekaer/stoneBlock/issues/390

**Closed by knoxhack** 2018-10-21 01:09 UTC
Labels: duplicate
