### ISSUE TITLE
AE2 Blocks De-Spawning

### ISSUE THREAD

**Issue by BrandonGamesYT** [Sunekaer/stoneBlock#310] opened 2018-10-10 07:47 UTC
## Bug Report

AE2 Blocks Disappearing at random (leaving empty [pretty much air blocks in there place]. Having to constantly make new AE2 Blocks
(Advanced inscriber, Pattern Encoder, Crystal Growth Chamber)

## Steps to Reproduce (for bugs)
1. Use any AE2 Blocks (The ones Listed) 
![image](https://user-images.githubusercontent.com/26289988/46720323-d8f3f600-cc35-11e8-9306-264d054fd4d9.png)

2. Having no idea when it happens, only notice it when I come back to this 
![image](https://user-images.githubusercontent.com/26289988/46720356-f4f79780-cc35-11e8-9645-3faf76ab7911.png)

## Logs
* Client/Server Log: 
* Crash Log:
* (Don't have full log atm, but here's a picture of something popping up that I think it could be)
![image](https://user-images.githubusercontent.com/26289988/46720629-bf9f7980-cc36-11e8-9d80-77c9be855600.png)

## Client Information
* Modpack Version: 1.0.17
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

**Comment by BrandonGamesYT** [comment] 2018-10-10 07:51
I am confirming when that message pops up the Advanced Inscribers despawn

![image](https://user-images.githubusercontent.com/26289988/46720885-50765500-cc37-11e8-9da4-6065628d2a1b.png)

**Comment by Sunekaer** [comment] 2018-10-10 09:21
gonna need the full log and debug log

**Comment by BrandonGamesYT** [comment] 2018-10-10 09:33
Debug- 
[debug.log](https://github.com/Sunekaer/stoneBlock/files/2464055/debug.log)

Lastest (Last Session Where it was Happening)
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2464021/latest.log)

Photo from in the Debug, seeming to signify the problem
![image](https://user-images.githubusercontent.com/26289988/46727196-a3570900-cc45-11e8-92f2-7a525e77879f.png)

**Comment by Sunekaer** [comment] 2018-10-10 09:51
okay i see on the last pic that they are dropped on the ground yea?
does it happen when the chunk unloads?

**Comment by BrandonGamesYT** [comment] 2018-10-10 09:54
Im not sure exactly why it happens, it happens alot when i move to quickly, go to other dimensions and if i go back to my base in time they will be dropped where they where placed, or they despawn

**Comment by Sunekaer** [comment] 2018-10-10 09:55
Okay so that sound like on chunk unloads

**Comment by Sunekaer** [comment] 2018-10-10 09:55
https://github.com/bdew/ae2stuff/issues/190

**Comment by Sunekaer** [comment] 2018-10-10 09:57
Do you have a security terminal connected to the AE2 stuff like in that one i just linked?

**Comment by BrandonGamesYT** [comment] 2018-10-10 09:57
Yes, i see someone else has the exact same problem, thank you

**Comment by xILikepuddingx** [comment] 2018-10-10 10:11
Is this a Server with sponge?

U can "fix" this with biometric Card without a binding

**Comment by xILikepuddingx** [comment] 2018-10-10 10:16
The problem is that the security terminal forgets you. by not granting access, ae2 stuff machines like to plop. From time to time, glass cables connected to the ae2 stuff machines are also affected.

Bug is since 1.10.2

**Comment by BrandonGamesYT** [comment] 2018-10-10 15:17
Nothing with the terminal is affected, Both my biometrics are still in (One blank and One of my own) and nothing happens to them (The Server is just running through the server files i got off of github

**Comment by xILikepuddingx** [comment] 2018-10-20 15:14
There will never be a fix for that

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3276

**Comment by Sunekaer** [comment] 2018-10-23 20:48
Closing as this probably never will be fixed

**Closed by Sunekaer** 2018-10-23 20:48 UTC
Labels: Awaiting fix from mod dev, Mod issue

**Comment by Carterpersall** [comment] 2021-08-19 22:05
There was an update over a year ago that supposedly fixed this bug.

https://github.com/nk2IsHere/ae2stuff/releases/tag/0.7.0.5
