### ISSUE TITLE
No pebble after breaking torch

### ISSUE THREAD

**Issue by domosplace** [Sunekaer/stoneBlock#36] opened 2018-08-02 17:55 UTC
Bug Report
No Pebbles after breaking torch

## Steps to Reproduce (for bugs)

1. Breaking stone with open gives pebbles
2.Breaks torch no more pebbles
3 slot in tool bar. Everywhere else works.

Modpack Version:1.0.8
Single Player

**Comment by Sunekaer** [comment] 2018-08-02 18:12
I cannot reproduce this
are you sure your using a empty hand to break the stone?

**Comment by domosplace** [comment] 2018-08-04 03:46
I can reproduce this every single time on server and single player.

**Comment by Sunekaer** [comment] 2018-08-04 16:12
can you send a video of this? or at screenshot of your hot bar

**Comment by knoxhack** [comment] 2018-08-04 17:41
Fixed in 1.0.9!

**Closed by knoxhack** 2018-08-04 17:41 UTC
