### ISSUE TITLE
Crash forge version 1.0.16

### ISSUE THREAD

**Issue by Nicocraft05** [Sunekaer/stoneBlock#155] opened 2018-09-23 11:41 UTC
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: serveur crash
* Crash Log:
[crash-2018-09-23_13.13.43-server.txt](https://github.com/Sunekaer/stoneBlock/files/2408675/crash-2018-09-23_13.13.43-server.txt)

## Client Information= Server

* Modpack Version:1.0.16
* Server/LAN/Single Player: server
* Optifine Installed:lol in 1.12 no version for modpack
* Shaders Enabled: no shader no time

**Comment by Sunekaer** [comment] 2018-09-23 11:51
upload the log to gist or pastebin....

**Comment by Nicocraft05** [comment] 2018-09-23 11:52
links or?

**Comment by Sunekaer** [comment] 2018-09-23 11:53
..... gist.github.com or pastebin.com ...

**Comment by Nicocraft05** [comment] 2018-09-23 11:58
https://pastebin.com/XY2wdnM0

**Comment by Sunekaer** [comment] 2018-09-23 12:04
Please post the latest log (logs/latest.log)

**Comment by Nicocraft05** [comment] 2018-09-23 12:05
the version server is tested for you or not?

**Comment by Sunekaer** [comment] 2018-09-23 12:06
do you mean if i have tested the server files?

**Comment by Nicocraft05** [comment] 2018-09-23 12:06
yes?

**Comment by Sunekaer** [comment] 2018-09-23 12:06
yes of course i test it before i upload it

**Comment by Nicocraft05** [comment] 2018-09-23 12:07
for windows?

**Comment by Sunekaer** [comment] 2018-09-23 12:07
yes...

**Comment by Sunekaer** [comment] 2018-09-23 12:07
now post the log or close the issue

**Comment by Nicocraft05** [comment] 2018-09-23 12:08
The LaunchServer.sh no function

**Comment by Nicocraft05** [comment] 2018-09-23 12:08
yes 2 minutes please

**Comment by Sunekaer** [comment] 2018-09-23 12:08
Because thats for linux...

**Comment by Nicocraft05** [comment] 2018-09-23 12:08
yes

**Comment by Nicocraft05** [comment] 2018-09-23 12:09
I already report x problem on your modpack

**Comment by Sunekaer** [comment] 2018-09-23 12:09
what

**Comment by Nicocraft05** [comment] 2018-09-23 12:10
xnet and wireless crafting terminal and ...

**Comment by Sunekaer** [comment] 2018-09-23 12:11
that has nothing to do with this crash....

**Comment by Nicocraft05** [comment] 2018-09-23 12:12
yes sorry but i love the modpack and I'm not alone waiting for the server launch

**Comment by Sunekaer** [comment] 2018-09-23 12:12
and but mods has been updated

**Comment by Nicocraft05** [comment] 2018-09-23 12:15
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2408695/latest.log)

**Comment by Sunekaer** [comment] 2018-09-23 12:16
.... gist or pastebin

**Comment by Nicocraft05** [comment] 2018-09-23 12:17
https://pastebin.com/dRcnsFZs

Sorry

**Comment by Sunekaer** [comment] 2018-09-23 12:26
"Unable to read the jar file Draconic-Evolution-1.12.2-2.3.14.308-universal.jar - ignoring
java.util.zip.ZipException: error in opening zip file"
this happens for many mods, looks like a permission issue or corrupt jars

**Comment by Nicocraft05** [comment] 2018-09-23 12:29
I tested 2 times the installation of the pack and tested the version 1.0.15 and as said no problem for the version 1.0.15.

Java: build 1.8.0_181-8u181-b13-1 ~ deb9u1-b13)

**Comment by Nicocraft05** [comment] 2018-09-23 12:32
one bug:
./LaunchServer.sh
-bash: ./LaunchServer.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by Sunekaer** [comment] 2018-09-23 12:33
try redownloading the mods or check permission or update java

**Comment by Sunekaer** [comment] 2018-09-23 12:33
Thats not a bug....

**Comment by Nicocraft05** [comment] 2018-09-23 12:33
I just did it

**Comment by Nicocraft05** [comment] 2018-09-23 12:34
for version linux no problem for windows?

**Comment by Sunekaer** [comment] 2018-09-23 12:35
LaunchServer.sh is for starting the server on linux NOT WINDOWS

**Comment by Nicocraft05** [comment] 2018-09-23 12:35
yes but my is linux

**Comment by Nicocraft05** [comment] 2018-09-23 12:37
I just did the version of windows I just tested and has no problem

**Comment by Sunekaer** [comment] 2018-09-23 12:39
did you update the LaunchServer.sh to the new one from the new files

**Comment by Nicocraft05** [comment] 2018-09-23 12:40
i have del your modpack simply and tried the command for the start.sh

**Comment by Sunekaer** [comment] 2018-09-23 12:44
start.sh?

**Comment by Nicocraft05** [comment] 2018-09-23 12:51
LaunchServer.sh

**Comment by Sunekaer** [comment] 2018-09-23 12:52
and what happened.......

**Comment by Nicocraft05** [comment] 2018-09-23 12:57
but you're crazy about me, the same problem since earlier just listen to me I do not have it to do I go because you soul me serious good holiday ever I hope

**Comment by Sunekaer** [comment] 2018-09-23 13:02
I have no clue what you are trying to say

**Closed** 2018-09-25 10:59 UTC
