### ISSUE TITLE
Server Will not Start

### ISSUE THREAD

**Issue by BlackroseDark** [Sunekaer/stoneBlock#407] opened 2018-10-19 19:05 UTC
Ive tried used libraries from the main download but cannot fix it. By using jopt-simple 5.0.3 instead of 4.6 i reduce the errors but cannot figure out the final steps to resolve. 
Paste 1 is fresh install
paste 2 is after swapping jopt files.

## Bug Report

When Starting the server file it seems some libraries are not included.

## Steps to Reproduce (for bugs)
extraxt new server files > sort eula> launcherserver.bat ERROR

## Logs
https://pastebin.com/t3rzdrhL
https://pastebin.com/YNACae8D
## Client Information

* Modpack Version: 1.0.22r1-server.zip
* Server/LAN/Single Player: LAN
* Optifine Installed: nope
* Shaders Enabled:none

**Comment by knoxhack** [comment] 2018-10-19 19:08
Duplicate of https://github.com/Sunekaer/stoneBlock/issues/390

**Closed by knoxhack** 2018-10-19 19:09 UTC

**Comment by BlackroseDark** [comment] 2018-10-19 19:19
Ahhh apologies new to git but was resolved thanks to sigfodrone
