### ISSUE TITLE
1.0.30 totally tanked my FPS

### ISSUE THREAD

**Issue by rsandell** [Sunekaer/stoneBlock#661] opened 2018-11-25 20:44 UTC
## Bug Report
I updated to 1.0.30 today and when I logged in my FPS was in the single digits, going up to 50 at times but mostly around 12. I'm low on entity count and the FPS is also the same in the mining dimension where I only have a vibrant capacitor bank, a flux plug and two solar panel VIII, so it doesn't seem to be something rendered. 
The time is fluctuating as well. But TPS is fine, right on 20.0.
I have a refined storage system running of course that seem to have some issues reading external storages at the moment as well (it is the only mod that got updated).

## Steps to Reproduce (for bugs)

1. Upgraded to 1.0.30 from 1.0.29
2. Login to single player world. 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.30
* Server/LAN/Single Player: Single Player
* Optifine Installed: Nope
* Shaders Enabled: None

**Comment by nzminecraftDOTcom** [comment] 2018-11-26 05:31
Nothing exploded or dropped a whole bunch of items in a mod update as a large inventory disappeared and you can't see the items?

**Comment by CharCharthemonkey** [comment] 2018-11-26 07:55
from wat ive seen its caused by refined storage (sorry raoul) when its either doing massive crafting or moving items from a disk to other storages (again sorry raoul) so double check if ure not crafting anything and if u are wait for it to finish then ure FPS/TPS "should" return and ive had the same issue and figured out that refined storage is atleats 70% the cause (and other stuff being the other 30% cause)

**Comment by alexdante** [comment] 2018-11-27 08:15
I've just upgraded to 1.0.30, FPS has dropped from 300+ to 10-30.

I get the same result from a newly created world as well.

**Comment by nzminecraftDOTcom** [comment] 2018-11-27 09:54
Perhaps post a few game logs perhaps something is being reported in there, even if the game isn't crashing. (Not a crash report)

**Comment by Sunekaer** [comment] 2018-11-27 13:54
Please report to refined storage so they can have a look at with you and find a solution

**Closed by Sunekaer** 2018-11-27 13:54 UTC
