### ISSUE TITLE
1.0.27 server crashes when a client joins

### ISSUE THREAD

**Issue by CyanSlinky** [Sunekaer/stoneBlock#591] opened 2018-11-12 15:42 UTC
## Bug Report

1.0.27 server crashes for me 100% of the time when a client joins, tried open to lan on both computers and tried running a dedicated server, always crashes. i then tried different versions, i started with 1.0.27r2(crashes) and then went down to 1.0.27(crashes) and then finally 1.0.26 which doesn't crash when a client joins but clients have empty quest books. I have no idea if this is only happening for me but it renders the modpack unplayable in multiplayer.

## Steps to Reproduce (for bugs)

1. Use version 1.0.27 and create a server, open to lan or dedicated
2. Make another player join the server.
3. Server crashes.

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/CyanSlinky/787f0a7809d031bf014a2c32c5ee8903

## Client Information

* Modpack Version: 1.0.27
* Server/LAN/Single Player: Server & LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by CDAGaming** [comment] 2018-11-12 15:57
@CyanSlinky Hello There, this issue seems weird as v1.4.9 of CraftPresence was meant to patch this?

If it is possible, Can you send me your CraftPresence Config (craftpresence.properties in your Mod Config folder) as well as If you were connecting to a LAN game or Hosting a LAN Game.

Thank You!

**Comment by CyanSlinky** [comment] 2018-11-12 16:14
[this](https://gist.github.com/CyanSlinky/a7df26fe309e833976f33bafb8d309a3) is from 1.0.26 as i downgraded to it as i explained in the original post, im currently reinstalling 1.0.27 from scratch and then im going to try to reproduce the bug, if it still happens i'll post the craftpresence.properties and crash logs from that.

**Comment by CyanSlinky** [comment] 2018-11-12 16:40
So i did a clean reinstall of the modpack and redownloaded the server files, started the dedicated server and tried to join it, the server didn't crash but it instantly disconnected me instead. Here's the server [latest.log](https://gist.github.com/CyanSlinky/6259dfbf329d0eb883e3d36a80324866) and here's my [latest.log](https://gist.github.com/CyanSlinky/6092b08196cc5de9c1fcc69a6719f2e3), also here's my [craftpresence.properties](https://gist.github.com/CyanSlinky/ce216a84e8aeada90612bbb17a71c50a) and the server's [craftpresence.properties](https://gist.github.com/CyanSlinky/28f12accadc06762f36d295a5e9aba0b). 

Also in my game when i look at the server in the list it says "StoneBlock 1.0.23" as the description, probably just something that was forgotten to change for the newer server files.

**Comment by CDAGaming** [comment] 2018-11-12 16:49
@CyanSlinky Letting you know that I have now Reproduced this issue. It's a minor NPE in getting the IP going from SP to LAN/Dedicated. Working on a Fix now...

**Comment by CDAGaming** [comment] 2018-11-12 18:12
Update: Turns out there were quite a few other Issues with LAN and my methods of updatingServerRPC. I am happy to say though that those issues, including this one, have been fixed in my workspace. Im testing some final things, then I'll be releasing v1.4.9.5 :D

Thank you for reporting this issue :D

**Comment by CDAGaming** [comment] 2018-11-13 17:23
v1.4.9.5 is now Fully Released on CurseForge for 1.6.4 - 1.13

1.12.2 Version: https://minecraft.curseforge.com/projects/craftpresence/files/2637750

**Comment by Sunekaer** [comment] 2018-11-13 21:52
StoneBlock-1.0.28

**Closed by Sunekaer** 2018-11-13 21:52 UTC
