### ISSUE TITLE
Extra Utilities RF generators "void" items fed into them

### ISSUE THREAD

**Issue by WRFleete** [Sunekaer/stoneBlock#426] opened 2018-10-21 06:47 UTC
## Bug Report

when feeding items into some (possibly all, I only tested a few I had in world) EU RF generators it tends to void the items fed into it
eg culinary generator, feeding melon, the stack number doesnt go up beyond the number that the pipe fed that tick (ender IO item conduit) , feeding manually does similar thing
slimey generator, milk works ok, feeding (additional) slime of any type doesnt increase stack count beyond 1 item and deletes item

## Steps to Reproduce (for bugs)

1. take an EU RF generator that takes stackable items
2. Feed manually or automatically the item of choice, 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 1.0.23
* Server/LAN/Single Player: SP
* Optifine Installed:
* Shaders Enabled:

**Comment by cubedtear** [comment] 2018-10-21 10:19
This issue has already been fixed in ExtraUtilities 2, in the commit https://github.com/rwtema/Extra-Utilities-2-Source/commit/993955750a3547a1d68738a222bcc72e3430cf4b. The following issues are related:
- rwtema/Extra-Utilities-2-Source#211
- rwtema/Extra-Utilities-2-Source#208
- rwtema/Extra-Utilities-2-Source#206 

The fix is released in ExtraUtilities 2 version 1.9.7, which is already released in curseforge, so updating it should fix it.

**Comment by luchokoldo** [comment] 2018-10-21 10:27
> This issue has already been fixed in ExtraUtilities 2, in the commit [rwtema/Extra-Utilities-2-Source@9939557](https://github.com/rwtema/Extra-Utilities-2-Source/commit/993955750a3547a1d68738a222bcc72e3430cf4b). The following issues are related:
> 
> * [rwtema/Extra-Utilities-2-Source#211](https://github.com/rwtema/Extra-Utilities-2-Source/issues/211)
> * [rwtema/Extra-Utilities-2-Source#208](https://github.com/rwtema/Extra-Utilities-2-Source/issues/208)
> * [rwtema/Extra-Utilities-2-Source#206](https://github.com/rwtema/Extra-Utilities-2-Source/issues/206)
> * [rwtema/Extra-Utilities-2-Source#204](https://github.com/rwtema/Extra-Utilities-2-Source/issues/204)
> 
> The fix is released in ExtraUtilities 2 version 1.9.7, which is already released in curseforge, so updating it should fix it.

this issue persist in 1.9.7 in MC 1.12.2

**Comment by WRFleete** [comment] 2018-10-21 12:12
downgraded to 1.9.5, removes the problem for now

**Comment by cubedtear** [comment] 2018-10-21 13:43
I compiled EU2 myself before 1.9.7 was released, and it fixed it for me, so I guessed the fix would be in 1.9.7. I guess it will make it for 1.9.8, but in the meantime 1.9.5 seems alright.

**Comment by Dragon911XX** [comment] 2018-10-22 17:48
Any word on how to downgrade to 1.9.5? It doesn't seem to give me the option in Twitch. I also read somewhere that version 1.0.23 fixes the issue, but it persists.

**Comment by WRFleete** [comment] 2018-10-22 19:01
> 
> 
> Any word on how to downgrade to 1.9.5? It doesn't seem to give me the option in Twitch. I also read somewhere that version 1.0.23 fixes the issue, but it persists.

click the profile for stoneblock
click on installed mods tab
scroll to extra utilities
click the extra utilities item
click the versions tab
click download on the desired version

**Comment by Sunekaer** [comment] 2018-10-23 20:44
could you test with 1.0.24

**Closed** 2018-10-24 20:51 UTC
Labels: Awaiting answer

**Comment by a20eac1d** [comment] 2018-11-09 18:45
Why is the issue closed?

The issue is still present in the latest version. The generators keep destroying items that I put into them.

**Comment by 0-x-2-2** [comment] 2018-11-10 01:48
Can confirm this is still present.
